# background_opacity = 1.0

[colors.primary]
background = "0x222222"
foreground = "0xffffff"

# [colors.primary.bright]
# black = "0x555753"
# blue = "0x729fcf"
# cyan = "0x34e2e2"
# green = "0x8ae234"
# magenta = "0xad7fa8"
# red = "0xef2929"
# white = "0xeeeeec"
# yellow = "0xfce94f"

# [colors.primary.normal]
# black = "0x2e3436"
# blue = "0x3465a4"
# cyan = "0x06989a"
# green = "0x4e9a06"
# magenta = "0x75507b"
# red = "0xcc0000"
# white = "0xd3d7cf"
# yellow = "0xc4a000"

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.normal]
family = "FreeMono"
style = "Bold"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
