[colors.primary]
background = "0x222222"
foreground = "0xffffff"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "FreeMono"
style = "Bold"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
